name: Build & Push Image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build:
    runs-on: docker-dind

    steps:
      - name: Install NodeJS
        run: apk --update add nodejs npm

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tags
        id: meta
        run: |
          IMAGE_NAME="${{ env.FORGEJO_REPOSITORY }}"
          TAGS=""

          # If generating image for a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            GIT_VERSION=${{ github.ref_name }}
            VERSION=${GIT_VERSION#v}
            TAGS=${{ vars.DOCKER_REGISTRY }}/${{ env.FORGEJO_REPOSITORY }}:${VERSION},${{ vars.DOCKER_REGISTRY }}/${{ env.FORGEJO_REPOSITORY }}:latest
          # If generating image merging to main
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            NPM_VERSION=$(node -p "require('./package.json').version")
            PREID=$(echo $NPM_VERSION | sed -n 's/.*\(\-\)\([a-zA-Z]\+\)\(\.[0-9]\+\)*$/\2/p')
            TAGS=${{ vars.DOCKER_REGISTRY }}/${{ env.FORGEJO_REPOSITORY }}:latest-${PREID}
          fi

          echo "tags=${TAGS}" >> $FORGEJO_OUTPUT
          echo "Generated tags: ${TAGS}"

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
