name: Build & Push Image

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    runs-on: docker-cli

    steps:
      - name: Install NodeJS
        run: apk --update add nodejs npm

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ env.FORGEJO_REPOSITORY }}:latest

# name: Build & Push Image
#
# on:
#   push:
#     branches:
#       - 'main'
#     tags:
#       - 'v*'
#
# jobs:
#
#   build:
#     runs-on: docker-dind
#
#     steps:
#       - name: Install NodeJS
#         run: apk --update add nodejs npm
#
#       - name: Checkout repository
#         uses: actions/checkout@v5
#         with:
#           fetch-depth: 0
#
#       - name: Login to registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ vars.DOCKER_REGISTRY }}
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}
#
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#
#       - name: Determine Docker tags
#         id: meta
#         run: |
#           DOCKER_TAGS=""
#           IMAGE_NAME="${{ env.FORGEJO_REPOSITORY }}"
#
#           # If generating image for a tag
#           if [[ "${{ github.ref_type }}" == "tag" ]]; then
#             VERSION=${{ github.ref_name }}
#             VERSION=${VERSION#v}
#             DOCKER_TAGS="$IMAGE_NAME:$VERSION,$IMAGE_NAME:latest"
#           # If generating image merging to main
#           elif [[ "${{ github.ref_name }}" == "main" ]]; then
#             VERSION=$(node -p "require('./package.json').version")
#             VERSION_NO_INCREMENT=$(echo $VERSION | cut -d'-' -f1)
#             DOCKER_TAGS="$IMAGE_NAME:$VERSION_NO_INCREMENT"
#           fi
#
#           echo "tags=${DOCKER_TAGS}" >> $FORGEJO_OUTPUT
#           echo "Generated tags: ${DOCKER_TAGS}"
#
#       - name: Build and push the Docker image
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: ./Dockerfile
#           target: production
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
