name: Build & Push Image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build:
    runs-on: docker-dind

    steps:
      - name: Install NodeJS
        run: apk --update add nodejs npm

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tags
        id: meta
        run: |
          VERSION=""
          IMAGE_NAME="${{ env.FORGEJO_REPOSITORY }}"

          # If generating image for a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            GIT_V=${{ github.ref_name }}
            VERSION=${GIT_V#v}
          # If generating image merging to main
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            NODE_V=$(node -p "require('./package.json').version")
            VERSION=$(echo $NODE_V | cut -d'-' -f1)
          fi

          echo "version=${VERSION}" >> $FORGEJO_OUTPUT
          echo "Generated version: ${VERSION}"

      - name: Validate generated tags
        run: |
          echo ${{ steps.meta.outputs.tags }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ env.FORGEJO_REPOSITORY }}:${{ steps.meta.outputs.version }}
