name: Manual Release & Build

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'The type of stable version bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      pre_id:
        description: 'The identifier for the next pre-release (e.g., SNAPSHOT, alpha, beta)'
        required: true
        default: 'SNAPSHOT'
        type: string

jobs:
  tag-and-release:
    runs-on: node-lts

    steps:

      - name: Install dependencies
        run: |
          apk --update add bash git
          git config --global user.email "forgejo@suroh.tk"
          git config --global user.name "Forgejo Action"

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ forgejo.head_ref }}


      - name: Create stable release version
        id: release_version
        run: |
          npm version ${{ forgejo.event.inputs.version_type }} -m "chore(release): release v%s"
          VERSION=$(node -p "require('./package.json').version")
          echo "version=${VERSION}" >> $FORGEJO_OUTPUT

      - name: Commit Git tag for the release
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          create_git_tag_only: true

      - name: Create next pre-release version
        run: |
          npm version pre${{ forgejo.event.inputs.version_type }} --preid ${{ forgejo.event.inputs.pre_id }} -m "chore: begin next development cycle"

      - name: Setup next development cycle
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          create_git_tag_only: true
