name: Tests

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 'lts/*' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run test:all
