name: Etherpad docker container build and push
run-name: Etherpad docker container build and push
on:
  push:
    branches:
      - 'main'
      - 'docker'
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: m3astwood/ethermap:latest
